name: ItsFridayThen

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  
      - uses: actions/checkout@v2

      - name: Execute python
        env:
          WEBHOOK: ${{ secrets.WEBHOOK }}
        run: |
          echo "${WEBHOOK}"
          python3 send-webhook.py
